### ISSUE TITLE
Team Doudna Code Review

### ISSUE THREAD

**Issue by lizchoi0918** [philippaSteinberg/EEP153-Proj4#10]
I liked how you organized the code into each separate deliverables. This makes it easy for me to follow the parts respective to the deliverables. 
Some suggestions I could give are: 
1) More explanation/elaboration on what you are doing in the code so that non-coders can also follow. I think if you could explain what the code chunks are for, it would be helpful for better understanding.
2) Depending on the policy you guys proposed, I think you can add the policy cost section. If you guys settled on a good to subsidize, you can use that good to see the deadweight-loss.

**Comment by Jaydenm5** [comment]
Thank you for reviewing our code and providing valuable feedback! (1) We tried keeping our code chunks concise and clear without too many explanation blurbs in an effort to keep the code short and elegant. I do agree it is helpful to have those explanations for those with less coding experience to follow along, but for the most part we drew inspiration from the coding that has been showed and explained in class by professor. (2) Our main policy we are proposing is educating farmers on how to grow more nutritious, local crops using ecological farming practices through agroecology education programs, so policy cost section will deviate slightly.
